version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:v0.10
    depends_on:
      - breedbase_db
    container_name: breedbase_web
    ports:
      - 7080:8080
    volumes:
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: ./sgn.conf
        target: /home/production/cxgn/sgn/sgn.conf
      - type: bind
        source: ./repos/famosolabbase
        target: /home/production/cxgn/famosolabbase
      - type: bind
        source: ./repos/famosolabbase/lsu_img
        target: /home/production/cxgn/sgn/documents/lsu_img
      - type: bind
        source: ./repos/sgn/t/data/fixture/empty_fixture.sql
        target: /home/production/cxgn/sgn/t/data/fixture/empty_fixture.sql
  breedbase_db:
    image: breedbase/pg:latest
    container_name: breedbase_db
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
    name: bb_postgres
