version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:v0.8
    depends_on:
      - breedbase_db
    container_name: breedbase_web
    ports:
      - 7080:8080
    volumes:
      - type: bind
        source: ./repos/sgn
        target: /home/production/cxgn/sgn
      - type: bind
        source: ./repos/famosolabbase
        target: /home/production/cxgn/famosolabbase
      - type: bind
        source: ./repos/famosolabbase/lsu_img
        target: /home/production/cxgn/sgn/documents/lsu_img
  breedbase_db:
    image: breedbase/pg:latest
    container_name: breedbase_db
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
    name: bb_postgres